# Generated by Django 5.0.10 on 2026-05-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TierPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_points_earned", models.IntegerField()),
                ("transaction_count", models.IntegerField()),
                ("drink_purchase_ratio", models.FloatField()),
                ("days_since_signup", models.IntegerField()),
                ("avg_points_per_transaction", models.FloatField()),
                ("predicted_tier", models.CharField(max_length=10)),
                ("probability_bronze", models.FloatField()),
                ("probability_silver", models.FloatField()),
                ("probability_gold", models.FloatField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolumeForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("forecast_date", models.DateField()),
                ("temperature_max", models.FloatField()),
                ("temperature_min", models.FloatField()),
                ("precipitation", models.FloatField(default=0.0)),
                ("day_of_week", models.IntegerField()),
                ("month", models.IntegerField()),
                ("coffee_price_usd", models.FloatField()),
                ("predicted_points", models.FloatField()),
                ("predicted_transactions", models.IntegerField()),
                ("recommended_reward_inventory", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "customer_id_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("customer_code", models.CharField(max_length=20, unique=True)),
                (
                    "membership_tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        default="bronze",
                        max_length=10,
                    ),
                ),
                ("current_points", models.IntegerField(default=0)),
                ("total_points_earned", models.IntegerField(default=0)),
                ("total_points_redeemed", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-total_points_earned"],
                "indexes": [
                    models.Index(
                        fields=["membership_tier"],
                        name="circle_cust_members_a75ad9_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("earn", "Earn"), ("redeem", "Redeem")], max_length=10
                    ),
                ),
                ("earn_source", models.CharField(blank=True, max_length=50)),
                ("points", models.IntegerField()),
                ("is_drink_purchase", models.BooleanField(default=False)),
                (
                    "drink_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("drink_price_jod", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        db_column="customer_id_hash",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="circle.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["transaction_type"],
                        name="circle_tran_transac_c98b93_idx",
                    ),
                    models.Index(
                        fields=["earn_source"], name="circle_tran_earn_so_8d2b6d_idx"
                    ),
                ],
            },
        ),
    ]
